Updated Travis build configuration
- Added some diagnostics within the git unshallowing activity that takes
  place during the before_install phase in order to have additional
  information to solve the issue
  https://github.com/travis-ci/travis-ci/issues/4942.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -11,7 +11,17 @@ jdk:
 services:
 - rabbitmq
 before_install:
-- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
+- if [[ -a .git/shallow ]]; 
+  then 
+    git fetch --unshallow --verbose; 
+    error=$?; 
+    if [[ $error -ne 1 ]]; 
+    then 
+      echo "Unshallowing failed with $error"; 
+      git --version; 
+      return $error; 
+    fi 
+  fi
 before_script:
 - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in target/config/ci/secring.gpg.enc -out local.secring.gpg -d
 - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in target/config/ci/pubring.gpg.enc -out local.pubring.gpg -d
